name: GitHub Actions Code Coverage

on:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v3

      # Java version
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Maven Build
      - name: GitHub Actions Build Maven project
        run: mvn -e package --file pom.xml
        
      - name: List current directories
        run: ls -a
        
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'


